---
#--------------------------------------------------------------------------------------------------------------------------------
# Playbook that installs Nginx that fronts the Codekvast services
#--------------------------------------------------------------------------------------------------------------------------------
- name: Nginx reverse proxy
  hosts: tag_role_backend
  user: ubuntu
  become: yes
  serial: 1

  vars_files:
  - vars/common.yml

  vars:
    nginx_vhosts:
      - listen: 80
        server_name: "{{ ec2_tag_LBCNAME0 }}"
        extra_parameters: |
          location / {
              proxy_pass http://localhost:{{ ports.dashboard.service }};
              proxy_buffering    off;
              proxy_set_header   X-Real-IP $remote_addr;
              proxy_set_header   X-Scheme $scheme;
              proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header   Host $http_host;
          }
      - listen: 80
        server_name: "{{ ec2_tag_LBCNAME1 }}"
        extra_parameters: |
          location / {
              proxy_pass http://localhost:{{ ports.login.service }};
              proxy_buffering    off;
              proxy_set_header   X-Real-IP $remote_addr;
              proxy_set_header   X-Scheme $scheme;
              proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header   Host $http_host;
          }
    nginx_remove_default_vhost: true

  pre_tasks:
  - file: path=/etc/nginx/sites-enabled/codekvast.conf state=absent

  roles:
  - geerlingguy.nginx

