# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Codekvast
email: codekvast@crisp.se
description: > # this means to ignore newlines until "baseurl:"
  Codekvast detects Truly Dead Code in Java applications. Truly Dead Code is code that is in production,
  but no real user has used for a certain period of time.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://codekvast.crisp.se" # the base hostname & protocol for your site
# twitter_username: ollehallin
github_username:  crispab/codekvast

# Build settings
markdown: kramdown
