---
- name: "Destroying {{ stack.env }} stack for customer '{{ stack.customer }}'"
  debug: var=stack
  when: _debug is defined and _debug

- name: Find correct VPC
  local_action:
    module: ec2_vpc_net_facts
    region: "{{ aws_region }}"
    profile: codekvast
    filters:
      cidr_block: "{{ stack.cidr_base }}.0.0/16"
      "tag:Name": "{{ aws_stack_name }}"
  register: net

- debug: var=net
  when: _debug is defined and _debug

- set_fact: vpc_id=net.vpcs[0].id

- name: Destroy VPC subnet
  local_action:
    module: ec2_vpc_subnet
    region: "{{ aws_region }}"
    profile: codekvast
    vpc_id: "{{ vpc_id }}"
    cidr: "{{ stack.cidr_base }}.1.0/24"
    state: "{{ stack.state }}"

- name: Destroy VPC
  local_action:
    module: ec2_vpc_net
    region: "{{ aws_region }}"
    profile: codekvast
    name: "{{ aws_stack_name }}"
    cidr_block: "{{ stack.cidr_base }}.0.0/16"
    state: "{{ stack.state }}"
