customer: "{{ hostvars[inventory_hostname]['ec2_tag_Customer'] }}"
env: "{{ hostvars[inventory_hostname]['ec2_tag_Env'] }}"
database_group_name: "tag_Name_Codekvast_{{ customer }}_{{ env }}_database"
codekvastVersion: "{{ lookup('ini', 'codekvastVersion type=properties file=../../gradle.properties') }}"
