warehouse:
  image: crisp/codekvast-warehouse:latest

  container_name: codekvast-warehouse

  volumes:
  - /tmp/codekvast/import:/tmp/codekvast
  - /var/log/codekvast:/var/log/codekvast

  links:
  - database

  environment:
  - SPRING_PROFILES_ACTIVE=docker
  - CODEKVAST_LOG_CONSOLE_THRESHOLD=INFO

database:
  image: mariadb:10

  container_name: codekvast-database

  environment:
  - MYSQL_ROOT_PASSWORD=root
  - MYSQL_DATABASE=codekvast_warehouse
  - MYSQL_USER=codekvast
  - MYSQL_PASSWORD=codekvast
  - TERM=xterm-256color

  volumes:
  - /var/lib/codekvast-database:/var/lib/mysql

  expose:
  - "3306"
