---
- name: Install unzip
  package: name=unzip state=present

- name: Download /root/AmazonCloudWatchAgent.zip
  get_url: url=https://s3.amazonaws.com/amazoncloudwatch-agent/linux/amd64/latest/AmazonCloudWatchAgent.zip dest=/root/AmazonCloudWatchAgent.zip

- name: Create installation directory
  file: path=/tmp/AmazonCloudWatchAgent state=directory

- name: Unpack /root/AmazonCloudWatchAgent.zip
  unarchive: src=/root/AmazonCloudWatchAgent.zip dest=/tmp/AmazonCloudWatchAgent/ copy=no

- name: Install /tmp/AmazonCloudWatchAgent/amazon-cloudwatch-agent.deb
  apt: deb=/tmp/AmazonCloudWatchAgent/amazon-cloudwatch-agent.deb state=present
  notify: Define amazon-cloudwatch-agent service

- name: Install /etc/logrotate.d/amazon-cloudwatch-agent
  copy: src=logrotate.d/amazon-cloudwatch-agent dest=/etc/logrotate.d/amazon-cloudwatch-agent

- name: Install CloudWatchAgent config
  template: src=amazon-cloudwatch-agent.json dest=/opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json
  notify: Restart amazon-cloudwatch-agent service
