---
- name: Install docker-cleanup in /etc/cron.daily
  template: src=docker-cleanup dest=/etc/cron.daily owner=root group=root mode=a=rx

- name: Add user to docker group
  user: name={{ actual_username }} groups=docker append=yes
