---
- hosts: all
  connection: local
  become: yes

  vars_files:
  - vars/secrets.yml

  handlers:
  - include: handlers/main.yml

  post_tasks:
  - {include: tasks/tools.yml, tags: tools}
  - {include: tasks/docker.yml, tags: docker}
  - {include: tasks/aws-cli.yml, tags: aws}
  - {include: tasks/google-chrome.yml, tags: chrome}
