---
- hosts: all
  connection: local
  become: yes

  vars:
  - docker_compose_version: 1.11.2
  - docker_machine_version: 0.10.0

  roles:
  - role: franklinkim.docker
  
  post_tasks:
  - include: tasks/compilers.yml
  - include: tasks/docker.yml
