---
- hosts: all
  connection: local
  become: yes

  roles:
  - {role: franklinkim.docker, tags: [docker, docker-engine]}
  
  post_tasks:
  - {include: tasks/compilers.yml, tags: compilers}
  - {include: tasks/docker.yml, tags: docker}
  - {include: tasks/yarn.yml, tags: yarn}
