---
- hosts: all
  connection: local
  become: yes

  vars_files:
  - vars/secrets.yml

  handlers:
  - include: handlers/main.yml

  roles:
  - {role: franklinkim.docker, tags: [docker, docker-engine]}
  
  post_tasks:
  - {include: tasks/compilers.yml, tags: compilers}
  - {include: tasks/docker.yml, tags: docker}
  - {include: tasks/yarn.yml, tags: yarn}
  - {include: tasks/aws-cli.yml, tags: aws}
