---
#-----------------------------------------------------------------------------------------------------------
# Playbook that installs the Codekvast Server application, which is an executable Spring Boot jar
#-----------------------------------------------------------------------------------------------------------
- name: Codekvast Server Application
  hosts: tag_role_backend
  user: ubuntu
  become: yes
  serial: 1

  vars_files:
  - vars/secrets.yml
  - vars/common.yml

  vars:
    codekvast_queue_path: /var/codekvast/queue
    codekvast_queue_pollIntervalSeconds: 30
    codekvast_webapp_jwtExpirationSeconds: 1800
    codekvast_heroku_codekvast_url: https://{{ codekvast_server_name }}
    codekvastVersion: "{{ lookup('ini', 'codekvastVersion type=properties file=../gradle.properties') }}"

  tasks:
  - name: Record EC2 facts
    action: ec2_facts

  - name: Take out of load balancer
    ec2_elb:
      instance_id: "{{ ansible_ec2_instance_id }}"
      state: absent
      wait: yes
      wait_timeout: 30
      region: "{{ aws_region }}"
      profile: codekvast
    connection: local
    become: no

  - name: Stop running service
    service: name=codekvast state=stopped
    ignore_errors: true

  - name: Wait until service has stopped
    wait_for: port=8080 state=stopped timeout=60

  - name: Install OpenJDK 8
    package: name=openjdk-8-jdk-headless state=installed
    notify: restart codekvast

  - name: Create codekvast group
    group: name=codekvast state=present

  - name: Create codekvast user
    user: name=codekvast group=codekvast state=present home=/opt/codekvast

  - name: Create directories
    file: path={{ codekvast_queue_path }} state=directory owner=codekvast group=codekvast

  - name: Install codekvast executable jar
    copy:
      src: ../product/warehouse/build/libs/codekvast-warehouse-{{ codekvastVersion }}-all.jar
      dest: /opt/codekvast/codekvast-warehouse-{{ codekvastVersion }}-all.jar
      owner: codekvast
      group: codekvast
      mode: 0700
    notify: restart codekvast

  # TODO: install a proper systemd codekvast.service file with an auto restart policy

  - name: Link the executable jar to /etc/init.d/codekvast
    file:
      src: /opt/codekvast/codekvast-warehouse-{{ codekvastVersion }}-all.jar
      dest: /etc/init.d/codekvast
      state: link
    notify: restart codekvast

  - name: Install Codekvast configuration file
    template: src=codekvast/application.properties dest=/opt/codekvast/application.properties owner=codekvast group=codekvast
    notify: restart codekvast

  - name: Enable codekvast service
    service: name=codekvast enabled=yes

  - name: Start codekvast service
    service: name=codekvast state=started

  - name: Wait until service has started
    wait_for: port=8080 state=started timeout=60

  - name: Register with load balancer
    ec2_elb:
      instance_id: "{{ ansible_ec2_instance_id }}"
      ec2_elbs: "{{ item }}"
      state: present
      wait: yes
      wait_timeout: 30
      region: "{{ aws_region }}"
      profile: codekvast
    with_items: "{{ ec2_elbs }}"
    connection: local
    become: no

  handlers:
  - name: restart codekvast
    service: name=codekvast state=restarted
