---
#-----------------------------------------------------------------------------------------------------------
# Playbook that installs the Codekvast Server application, which is an executable Spring Boot jar
#-----------------------------------------------------------------------------------------------------------
- name: Codekvast Server Application
  hosts: all
  become: yes

  vars_files:
  - vars/secrets.yml
  - vars/common.yml

  vars:
    codekvast_queue_path: /var/codekvast/queue
    codekvast_queue_pollIntervalSeconds: 30
    codekvast_webapp_jwtExpirationSeconds: 1800
    codekvast_heroku_codekvast_url: https://{{ codekvast_server_name }}
    codekvastVersion: "{{ lookup('ini', 'codekvastVersion type=properties file=../gradle.properties') }}"

  tasks:
  - debug: var=codekvastVersion

  - name: Install OpenJDK 8
    package: name=openjdk-8-jdk-headless state=installed
    notify: restart codekvast

  - name: Create codekvast group
    group: name=codekvast state=present

  - name: Create codekvast user
    user: name=codekvast group=codekvast state=present home=/opt/codekvast

  - name: Create directories
    file: path={{ codekvast_queue_path }} state=directory owner=codekvast group=codekvast

  - name: Install codekvast executable jar
    copy:
      src: ../product/warehouse/build/libs/codekvast-warehouse-{{ codekvastVersion }}-all.jar
      dest: /opt/codekvast/codekvast-warehouse-{{ codekvastVersion }}-all.jar
      owner: codekvast
      group: codekvast
      mode: 0700
    notify: restart codekvast

  - name: Link /etc/init.d/codekvast to executable jar
    file:
      src: /opt/codekvast/codekvast-warehouse-{{ codekvastVersion }}-all.jar
      dest: /etc/init.d/codekvast
      state: link
    notify: restart codekvast

  - name: Install Codekvast configuration file
    template: src=codekvast/application.properties dest=/opt/codekvast/application.properties owner=codekvast group=codekvast
    notify: restart codekvast

  - name: Define and start codekvast service
    service: name=codekvast enabled=yes state=started

  handlers:
  - name: restart codekvast
    service: name=codekvast state=restarted
