---
#---------------------------------------------------------------
# Playbook which provisions the AWS resources
#---------------------------------------------------------------
- name: AWS resources
  hosts: all
  connection: local
  gather_facts: no

  vars:

  tasks:
  - name: Write DNS records
    route53:
      command: "{{ item.command | default('create') }}"
      overwrite: yes
      record: "{{ item.name }}"
      ttl: "{{ item.ttl | default('7200') }}"
      type: "{{ item.type | default('CNAME') }}"
      value: "{{ item.value }}"
      zone: codekvast.io
      profile: codekvast # in ~/.boto
    with_items:
    - { name: 'www.codekvast.io', value: crispab.github.io, owner: olle }
    loop_control:
      label: "{{ item.name }}"
