---
#-----------------------------------------------------------------------------------------------------------
# Playbook that installs the Codekvast Database, which is served by MariaDB
#-----------------------------------------------------------------------------------------------------------
- name: Codevast Database Server
  hosts: tag_role_database
  user: ubuntu
  become: yes

  vars_files:
  - vars/secrets.yml

  vars:
    mysql_origin: 'default'
    mysql_vendor: 'mariadb'
    mariadb_version: '10.1'
    mysql_backup_dir: '/var/backups/mariadb'
    mysql_extra_configuration:
      character_set_server: 'utf8'
      collation_server: 'utf8_general_ci'

    mysql_databases:
    - codekvast

    mysql_users:
    - name: 'codekvast'
      password: '{{ mysql_application_password }}'
      priv: codekvast.*:ALL
      host: '%'

  roles:
  - {role: HanXHX.mysql, tags: mariadb}

  post_tasks:
  - name: Install backup scripts
    template: src=database/{{ item }}.j2 dest=/root/{{ item }} mode=755
    with_items:
    - mariadb-backup
    - mariadb-restore

  - name: Link /root/mariadb-backup to /etc/cron.daily
    file: src=/root/mariadb-backup dest=/etc/cron.daily/mariadb-backup state=link
