---
#---------------------------------------------------------------
# Playbook which provisions the shared infrastructure
#---------------------------------------------------------------
- name: Shared AWS infrastructure
  hosts: localhost
  connection: local
  gather_facts: no

  vars_files:
    - vars/common.yml
    - vars/secrets.yml

  vars:
    dns_records:
    - { name: 'www.codekvast.io', value: crispab.github.io, owner: olle }


  pre_tasks:
  - name: Create static DNS records
    local_action:
      module: route53
      profile: codekvast # in ~/.boto
      zone: codekvast.io
      command: "{{ item.command | default('create') }}"
      overwrite: yes
      record: "{{ item.name }}"
      ttl: "{{ item.ttl | default('7200') }}"
      type: "{{ item.type | default('CNAME') }}"
      value: "{{ item.value }}"
    with_items: "{{ dns_records }}"
    loop_control:
      label: "{{ item.name }}"

  roles:
  - role: codekvast.aws-stack
    customer: Demo
    env: staging
    vpc_cidr_base: "10.0"
    stack_state: present
    stack_dns_names:
    - api-staging
    - app-staging