---
#-----------------------------------------------------------------------------------------------------------
# Playbook that installs Nginx, which acts as a SSL terminator for the Codekvast Server app.
# It uses the Let's Encrypt certbot for automatic SSL certificate management.
# TODO: Implement certbot
#-----------------------------------------------------------------------------------------------------------
- name: Codekvast Nginx configuration
  hosts: tag_role_webserver
  user: ubuntu
  become: yes

  vars_files:
  - vars/common.yml

  vars:
    nginx_vhosts:
    - listen: "443 default_server"
      server_name: "default"
      extra_parameters: |
        ssl on;
        ssl_certificate           /etc/ssl/certs/ssl-cert-snakeoil.pem;
        ssl_certificate_key       /etc/ssl/private/ssl-cert-snakeoil.key;

        location / {
          proxy_pass http://localhost:8080;

          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;

          proxy_redirect http://localhost:8080 https://{{ codekvast_server_name }};
        }

  pre_tasks:
  - name: Install ssl-cert package
    apt: name=ssl-cert state=installed

  - name: make-ssl-cert generate-default-snakeoil
    shell: make-ssl-cert generate-default-snakeoil creates=/etc/ssl/certs/ssl-cert-snakeoil.pem

  roles:
  - geerlingguy.nginx

  post_tasks:
  - include: tasks/nginx-certbot.yml
    when: vagrantMode is not defined
