---
- name: Find correct VPC
  local_action:
    module: ec2_vpc_net_facts
    region: "{{ aws_region }}"
    profile: codekvast
    filters:
      cidr_block: "{{ vpc_cidr_base }}.0.0/16"
      "tag:Name": "{{ aws_resource_name }}"
  register: net

- debug: var=net.vpcs[0].id

- set_fact: vpc_id=net.vpcs[0].id

- name: Destroy VPC subnet
  local_action:
    module: ec2_vpc_subnet
    region: "{{ aws_region }}"
    profile: codekvast
    vpc_id: "{{ vpc_id }}"
    cidr: "{{ vpc_cidr_base}}.1.0/24"
    state: "{{ stack_state }}"

- name: Destroy VPC
  local_action:
    module: ec2_vpc_net
    region: "{{ aws_region }}"
    profile: codekvast
    name: "{{ aws_resource_name }}"
    cidr_block: "{{ vpc_cidr_base }}.0.0/16"
    state: "{{ stack_state }}"
