---
#---------------------------------------------------------------
# Playbook which provisions the AWS infrastructure
#---------------------------------------------------------------
- name: AWS infrastructure stack
  hosts: all[0]
  connection: local
  gather_facts: no

  vars_files:
    - vars/common.yml
    - vars/secrets.yml

  vars:
    static_web_sites:
    - { name: 'downloads.codekvast.io', region: 'eu-central-1' }

    dns_records:
    - { name: 'codekvast.io', type: A, alias: True, alias_zone_id: 'Z21DNDUVLTQW6Q', value: 's3-website.eu-central-1.amazonaws.com', owner: olle }
    - { name: 'www.codekvast.io', type: A, alias: True, alias_zone_id: 'Z21DNDUVLTQW6Q', value: 's3-website.eu-central-1.amazonaws.com', owner: olle }

  tasks:
  - name: Create S3 buckets for static websites
    local_action:
      module: s3_bucket
      profile: codekvast
      region: "{{ item.region }}"
      name: "{{ item.name }}"
      tags:
        Owner: Codekvast
    with_items: "{{ static_web_sites }}"
    loop_control:
      label: "{{ item.name }}"
    tags:
    - static-web-sites

  - name: Configure S3 buckets for static websites
    local_action:
      module: s3_website
      profile: codekvast
      region: "{{ item.region }}"
      name: "{{ item.name }}"
      state: present
    with_items: "{{ static_web_sites }}"
    loop_control:
      label: "{{ item.name }}"
    tags:
    - static-web-sites

  - name: Create CNAMES for static websites
    local_action:
      module: route53
      profile: codekvast # in ~/.boto
      zone: codekvast.io
      command: "{{ item.command | default('create') }}"
      overwrite: yes
      record: "{{ item.name }}"
      type: CNAME
      value: "{{ item.name }}.s3-website.{{ item.region }}.amazonaws.com"
      ttl: "{{ item.ttl | default('7200') }}"
    with_items: "{{ static_web_sites }}"
    loop_control:
      label: "{{ item.name }}"
    tags:
    - static-web-sites

  - name: Create static DNS records
    local_action:
      module: route53
      profile: codekvast # in ~/.boto
      zone: codekvast.io
      command: "{{ item.command | default('create') }}"
      overwrite: yes
      record: "{{ item.name }}"
      ttl: "{{ item.ttl | default('7200') }}"
      type: "{{ item.type | default('CNAME') }}"
      value: "{{ item.value }}"
      alias: "{{ item.alias | default(False) }}"
      alias_hosted_zone_id: "{{ item.alias_zone_id | default(None) }}"
    with_items: "{{ dns_records }}"
    loop_control:
      label: "{{ item.name }}"
    tags:
    - dns

  - name: Create AWS stacks
    include_role: name=codekvast.aws-stack
    with_items: "{{ aws_stacks }}"
    loop_control:
      loop_var: stack
    tags:
    - aws
    - infra
