---
#-----------------------------------------------------------------------------------------------------------
# Playbook for doing operating system maintenance
#-----------------------------------------------------------------------------------------------------------
- name: Codekvast Server
  hosts: all
  user: ubuntu
  become: yes

  tasks:
  - name: Install swedish language pack
    package: name=language-pack-sv state=present

  - name: Upgrade installed packages
    apt: update_cache=yes upgrade=safe autoremove=yes purge=yes
